# Site settings
author: Thomas Dubiel
title: The Programmer's Journey
header-img: img/home-bg.png
email: td1729@hotmail.com
copyright_name: Thomas Dubiel
description: > # this means to ignore newlines until "baseurl:"
  Road To Becoming A Software Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  goodjobbin85

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
